# Generated by Django 4.1.7 on 2023-03-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('covertedImage', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
