# Generated by Django 4.1.7 on 2023-03-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addWatermark', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='convertimage',
            name='imageId',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
