# Generated by Django 4.1.7 on 2023-03-27 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addWatermark', '0002_convertimage_imageid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='convertimage',
            old_name='covertedImage',
            new_name='convertedImage',
        ),
    ]
