# Generated by Django 4.1.7 on 2023-03-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addWatermark', '0003_rename_covertedimage_convertimage_convertedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertedVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convertedVideo', models.FileField(blank=True, null=True, upload_to='storage/convertedVideos/')),
                ('convertedVideoId', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='storage/videos/')),
                ('videoId', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WaterMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waterMark', models.ImageField(blank=True, null=True, upload_to='storage/waterMarks/')),
                ('waterMarkId', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='ConvertImage',
        ),
    ]
