# Generated by Django 4.1.7 on 2023-03-27 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addWatermark', '0004_convertedvideos_video_watermarks_delete_convertimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Video',
            new_name='Videos',
        ),
    ]
