# Generated by Django 4.1.7 on 2023-03-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addWatermark', '0005_rename_video_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waterMark', models.ImageField(blank=True, null=True, upload_to='storage/waterMarks/')),
                ('video', models.FileField(blank=True, null=True, upload_to='storage/videos/')),
                ('haseDataId', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Videos',
        ),
        migrations.DeleteModel(
            name='WaterMarks',
        ),
    ]
