# Generated by Django 4.1.7 on 2023-03-27 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addWatermark', '0006_basedata_delete_videos_delete_watermarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basedata',
            old_name='haseDataId',
            new_name='baseDataId',
        ),
    ]
